# Generated by Django 3.1.7 on 2021-03-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='diary',
            name='mood',
            field=models.IntegerField(choices=[(0, 'brilliant'), (1, 'good'), (2, 'meh'), (3, 'bad'), (4, 'awful')]),
        ),
        migrations.DeleteModel(
            name='DiaryImage',
        ),
    ]
