# Generated by Django 3.1.7 on 2021-03-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210323_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diary.diary')),
            ],
        ),
    ]
